/**
 * Content Collections — replaces Webflow CMS (`w-dyn-list`/`w-dyn-item`),
 * MIGRATION-GUIDE Phase 3. Entries generated by `scripts/extract-content.mjs`
 * from the raw export; image URLs are still CDN links until Phase 5
 * (asset localization) rewrites them to /assets/.
 */
import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const cdnImage = z.string().startsWith("https://cdn.prod.website-files.com/").or(z.literal(""));

const services = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/services" }),
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    image: cdnImage.optional(),
    order: z.number().optional(),
  }),
});

const portfolio = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/portfolio" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    heroImage: cdnImage.optional(),
    gallery: z.array(cdnImage).default([]),
  }),
});

const posts = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/posts" }),
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    date: z.coerce.date(),
    category: z.string(),
    heroImage: cdnImage.optional(),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/categories" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
  }),
});

const team = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/team" }),
  schema: z.object({
    name: z.string(),
    role: z.string().optional(),
    bio: z.string().optional(),
    photo: cdnImage.optional(),
  }),
});

export const collections = { services, portfolio, posts, categories, team };
