/**
 * Content Collections — replaces Webflow CMS (`w-dyn-list`/`w-dyn-item`),
 * MIGRATION-GUIDE Phase 3. Entries generated by `scripts/extract-content.mjs`
 * from the raw export; image paths were localized to /assets/ in Phase 5
 * by `scripts/localize-assets.mjs` (map: scripts/asset-map.json).
 */
import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const assetImage = z.string().startsWith("/assets/").or(z.literal(""));

const services = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/services" }),
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    image: assetImage.optional(),
    order: z.number().optional(),
  }),
});

const portfolio = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/portfolio" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    heroImage: assetImage.optional(),
    gallery: z.array(assetImage).default([]),
  }),
});

const posts = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/posts" }),
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    date: z.coerce.date(),
    category: z.string(),
    heroImage: assetImage.optional(),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/categories" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
  }),
});

const team = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/team" }),
  schema: z.object({
    name: z.string(),
    role: z.string().optional(),
    bio: z.string().optional(),
    photo: assetImage.optional(),
  }),
});

export const collections = { services, portfolio, posts, categories, team };
